#!/usr/bin/python3
import pyfiglet
import argparse
import os
from time import monotonic, sleep
import shutil
from plyer import notification


parser = argparse.ArgumentParser(
    description="This is a CLI tool for pomodoro"
)


parser.add_argument('--desc',
                    default=None,
                    type=str)
parser.add_argument('-t', '--time',
                    default=25,
                    help='time in minutes',
                    type=int)
parser.add_argument('-c', '--category',
                    default=None,
                    type=str)
parser.add_argument('-f', '--font',
                    default='colossal',
                    type=str)

args = parser.parse_args()

category = args.category
desc = args.desc
duration = args.time * 60
font = args.font


f = pyfiglet.Figlet(font=font)


def DrawText(text, center=True):
    if center:
        print(*[x.center(shutil.get_terminal_size().columns)
              for x in f.renderText(text).split("\n")], sep="\n")
    else:
        print(f.renderText(text))


def print_on_screen(_TIME: int) -> None:
    m, s = divmod(_TIME, 60)
    h, m = divmod(m, 60)
    h, m, s = str(h), str(m), str(s)
    text = f'{h.zfill(2)} : {m.zfill(2)} : {s.zfill(2)}'
    os.system('clear')
    DrawText(text, center=True)


def Success() -> None:
    os.system('clear')
    text = 'Average Work'
    DrawText(text)


for t in range(duration, -1, -1):
    start = monotonic()
    print_on_screen(t)
    sleep(1 - monotonic() + start)
Success()


notification.notify(
    title='Average Work!',
    message='Timer Completed',
    app_name='Pomodoro',
)
